# -*- coding: utf-8 -*-
"""konversi_hari

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v5kJLCb6oOmdMv-Bh4bd-gWzSO0ayTQu
"""

#membuat modul
#modul konversi_hari.py

def jam(hari):
    print(f"Konversi {hari} hari ke jam: {hari*24} jam")

def menit(hari):
    print(f"Konversi {hari} hari ke menit: {hari*1440} menit")

def detik(hari):
    print(f"Konversi {hari} hari ke detik: {hari*86400} detik")